CONSTITUENTS_CURRENT

In [ ]:
import pandas as pd
url = "https://en.wikipedia.org/wiki/NIFTY_50"

# Read all tables from the Wikipedia page
tables = pd.read_html(url)

# Find the table with all 4 required columns
target_df = None
for table in tables:
    if {"Company name", "Symbol", "Sector[15]", "Date added[16]"}.issubset(table.columns):
        target_df = table
        break

# If table not found
if target_df is None:
    raise ValueError("NIFTY 50 constituents table not found. Page structure may have changed.")

# Rename columns
target_df = target_df.rename(columns={
    "Company name": "Company Name",
    "Symbol": "Symbol",
    "Sector[15]": "Sector",
    "Date added[16]": "Date Added"
})

# Reorder and keep only needed columns
nifty_df = target_df[["Company Name", "Symbol", "Sector", "Date Added"]]
print(nifty_df)

                       Company Name      Symbol  \
0                 Adani Enterprises    ADANIENT
1                 Adani Ports & SEZ  ADANIPORTS
2                  Apollo Hospitals  APOLLOHOSP
3                      Asian Paints  ASIANPAINT
4                         Axis Bank    AXISBANK
5                        Bajaj Auto  BAJAJ-AUTO
6                     Bajaj Finance  BAJFINANCE
7                     Bajaj Finserv  BAJAJFINSV
8                Bharat Electronics         BEL
9                     Bharti Airtel  BHARTIARTL
10                            Cipla       CIPLA
11                       Coal India   COALINDIA
12         Dr. Reddy's Laboratories     DRREDDY
13                    Eicher Motors   EICHERMOT
14                          Eternal     ETERNAL
15                Grasim Industries      GRASIM
16                          HCLTech     HCLTECH
17                        HDFC Bank    HDFCBANK
18                        HDFC Life    HDFCLIFE
19                    Hero MotoCorp  HEROMOTOCO
20              Hindalco Industries    HINDALCO
21               Hindustan Unilever  HINDUNILVR
22                       ICICI Bank   ICICIBANK
23                    IndusInd Bank  INDUSINDBK
24                          Infosys        INFY
25                              ITC         ITC
26           Jio Financial Services      JIOFIN
27                        JSW Steel    JSWSTEEL
28              Kotak Mahindra Bank   KOTAKBANK
29                  Larsen & Toubro          LT
30              Mahindra & Mahindra         M&M
31                    Maruti Suzuki      MARUTI
32                     Nestlé India   NESTLEIND
33                             NTPC        NTPC
34  Oil and Natural Gas Corporation        ONGC
35                       Power Grid   POWERGRID
36              Reliance Industries    RELIANCE
37       SBI Life Insurance Company     SBILIFE
38                  Shriram Finance  SHRIRAMFIN
39              State Bank of India        SBIN
40                       Sun Pharma   SUNPHARMA
41        Tata Consultancy Services         TCS
42           Tata Consumer Products  TATACONSUM
43                      Tata Motors  TATAMOTORS
44                       Tata Steel   TATASTEEL
45                    Tech Mahindra       TECHM
46                    Titan Company       TITAN
47                            Trent       TRENT
48                 UltraTech Cement  ULTRACEMCO
49                            Wipro       WIPRO

                            Sector            Date Added
0                  Metals & Mining     30 September 2022
1                         Services     28 September 2015
2                       Healthcare         31 March 2022
3                Consumer Durables      27 April 2012[a]
4               Financial Services         27 March 2009
5   Automobile and Auto Components     1 October 2010[b]
6               Financial Services     29 September 2017
7               Financial Services          2 April 2018
8                    Capital Goods     30 September 2024
9                Telecommunication          1 March 2004
10                      Healthcare        7 October 1998
11     Oil, Gas & Consumable Fuels       10 October 2011
12                      Healthcare     1 October 2010[c]
13  Automobile and Auto Components          1 April 2016
14               Consumer Services         28 March 2025
15          Construction Materials       2 April 2018[d]
16          Information Technology       28 October 2002
17              Financial Services         22 April 1996
18              Financial Services          31 July 2020
19  Automobile and Auto Components     7 October 1998[e]
20                 Metals & Mining         22 April 1996
21      Fast Moving Consumer Goods         22 April 1996
22              Financial Services       25 January 2002
23              Financial Services          1 April 2013
24          Information Technology        7 October 1998
25      Fast Moving Consumer Goods         22 April 1996
26              Financial Services         28 March 2025
27                 Metals & Mining     28 September 2018
28              Financial Services          8 April 2010
29                    Construction   10 December 2004[f]
30  Automobile and Auto Components     18 September 1996
31  Automobile and Auto Components          1 March 2004
32      Fast Moving Consumer Goods  27 September 2019[g]
33                           Power     24 September 2007
34     Oil, Gas & Consumable Fuels         12 April 2004
35                           Power         14 March 2008
36     Oil, Gas & Consumable Fuels         22 April 1996
37              Financial Services     25 September 2020
38              Financial Services         28 March 2024
39              Financial Services         22 April 1996
40                      Healthcare       17 January 2002
41          Information Technology      25 February 2005
42      Fast Moving Consumer Goods      31 March 2021[h]
43  Automobile and Auto Components         22 April 1996
44                 Metals & Mining         22 April 1996
45          Information Technology         28 March 2014
46               Consumer Durables          2 April 2018
47               Consumer Services     30 September 2024
48          Construction Materials     28 September 2012
49          Information Technology  27 September 2013[i]

PAST_CONSTITUENTS

In [ ]:
import pandas as pd
url = "https://en.wikipedia.org/wiki/NIFTY_50"
tables = pd.read_html(url, header=[0, 1])  # MultiIndex
changes_df = tables[2]  # This is the "Index changes" table

# Step 2: Drop the last column (Ref), keep first 4
changes_df = changes_df.iloc[:, :4]

# Step 3: Rename columns manually
changes_df.columns = ["Excluded", "Included", "Date", "Reason"]
print(changes_df.head())

                        Excluded                 Included  \
0           Constituent excluded     Constituent included
1  Shipping Corporation of India            Siemens India
2                 Tata Chemicals                   Suzlon
3                       Tata Tea  Reliance Communications
4                    Jet Airways       Reliance Petroleum

                  Date                            Reason
0  Date of replacement              Reason for exclusion
1         27 June 2006  Inadequate market capitalization
2         27 June 2006  Inadequate market capitalization
3     1 September 2006  Inadequate market capitalization
4         4 April 2007  Inadequate market capitalization

In [ ]:
current_nifty = nifty_df['Company Name'].tolist()

In [ ]:
changes_df = changes_df.drop(index=0).reset_index(drop=True)

In [ ]:
changes_df

,Excluded,Included,Date,Reason
0,Shipping Corporation of India,Siemens India,27 June 2006,Inadequate market capitalization
1,Tata Chemicals,Suzlon,27 June 2006,Inadequate market capitalization
2,Tata Tea,Reliance Communications,1 September 2006,Inadequate market capitalization
3,Jet Airways,Reliance Petroleum,4 April 2007,Inadequate market capitalization
4,Oriental Bank of Commerce,Sterlite Industries,4 April 2007,Inadequate market capitalization
...,...,...,...,...
60,UPL,Shriram Finance,28 March 2024,Inadequate market capitalization
61,Divi's Laboratories,Bharat Electronics,30 September 2024,Inadequate market capitalization
62,LTIMindtree,Trent,30 September 2024,Inadequate market capitalization
63,Bharat Petroleum,Jio Financial Services,28 March 2025,Inadequate market capitalization
64,Britannia Industries,Eternal,28 March 2025,Inadequate market capitalization

In [ ]:
changes_df_rev = changes_df[::-1]
changes_df_rev

,Excluded,Included,Date,Reason
64,Britannia Industries,Eternal,28 March 2025,Inadequate market capitalization
63,Bharat Petroleum,Jio Financial Services,28 March 2025,Inadequate market capitalization
62,LTIMindtree,Trent,30 September 2024,Inadequate market capitalization
61,Divi's Laboratories,Bharat Electronics,30 September 2024,Inadequate market capitalization
60,UPL,Shriram Finance,28 March 2024,Inadequate market capitalization
...,...,...,...,...
4,Oriental Bank of Commerce,Sterlite Industries,4 April 2007,Inadequate market capitalization
3,Jet Airways,Reliance Petroleum,4 April 2007,Inadequate market capitalization
2,Tata Tea,Reliance Communications,1 September 2006,Inadequate market capitalization
1,Tata Chemicals,Suzlon,27 June 2006,Inadequate market capitalization
0,Shipping Corporation of India,Siemens India,27 June 2006,Inadequate market capitalization

In [ ]:
current_nifty_cp = current_nifty.copy()

In [ ]:
## grouping with same dates
import pandas as pd

grouped_df = changes_df_rev.groupby('Date', sort = False).agg({
    'Excluded': list,
    'Included': list
}).reset_index()
print(grouped_df.head())

                Date                                  Excluded  \
0      28 March 2025  [Britannia Industries, Bharat Petroleum]
1  30 September 2024        [LTIMindtree, Divi's Laboratories]
2      28 March 2024                                     [UPL]
3       13 July 2023                                    [HDFC]
4  30 September 2022                            [Shree Cement]

                            Included
0  [Eternal, Jio Financial Services]
1        [Trent, Bharat Electronics]
2                  [Shriram Finance]
3                      [LTIMindtree]
4                [Adani Enterprises]

In [ ]:
current_nifty_cp = current_nifty.copy()
yearwise_dict = {}
# for i in range(changes_df_rev.shape[0]):
for i in range(grouped_df.shape[0]):
  index = current_nifty_cp.copy()
  # print(index)
  date = grouped_df.iloc[i]['Date']
  included = grouped_df.iloc[i]['Included']
  excluded = grouped_df.iloc[i]['Excluded']
  print(date, included, excluded)
  for i in included:
    if i not in index:
      index.append(i)
  for i in excluded:
    if i in index:
      index.remove(i)
  # print(index)

  yearwise_dict[date] = index
  index_changed = index.copy()
  # ## now to do back reconstruction, remove included and add excluded
  for i in included:
    index_changed.remove(i)
  for i in excluded:
    index_changed.append(i)
  # print(index_changed)

  current_nifty_cp = index_changed

28 March 2025 ['Eternal', 'Jio Financial Services'] ['Britannia Industries', 'Bharat Petroleum']
30 September 2024 ['Trent', 'Bharat Electronics'] ['LTIMindtree', "Divi's Laboratories"]
28 March 2024 ['Shriram Finance'] ['UPL']
13 July 2023 ['LTIMindtree'] ['HDFC']
30 September 2022 ['Adani Enterprises'] ['Shree Cement']
31 March 2022 ['Apollo Hospitals'] ['Indian Oil Corporation']
31 March 2021 ['Tata Consumer Products'] ['GAIL']
25 September 2020 ["Divi's Laboratories", 'SBI Life Insurance Company'] ['Bharti Infratel', 'Zee Entertainment Enterprises']
31 July 2020 ['HDFC Life'] ['Vedanta']
19 March 2020 ['Shree Cement'] ['Yes Bank']
27 September 2019 ['Nestlé India'] ['Indiabulls Housing Finance']
29 March 2019 ['Britannia Industries'] ['Hindustan Petroleum']
28 September 2018 ['JSW Steel'] ['Lupin']
2 April 2018 ['Titan Company', 'Grasim Industries', 'Bajaj Finserv'] ['Bosch India', 'Aurobindo Pharma', 'Ambuja Cements']
29 September 2017 ['UPL', 'Hindustan Petroleum', 'Bajaj Finance'] ['Tata Power', 'Bank of Baroda', 'ACC']
26 May 2017 ['Vedanta'] ['Grasim Industries']
31 March 2017 ['Indian Oil Corporation', 'Indiabulls Housing Finance'] ['Idea Cellular', 'BHEL']
1 April 2016 ['Eicher Motors', 'Bharti Infratel', 'Aurobindo Pharma'] ['Vedanta', 'Punjab National Bank', 'Cairn India']
28 September 2015 ['Adani Ports & SEZ'] ['NMDC']
29 May 2015 ['Bosch India'] ['IDFC']
27 March 2015 ['Yes Bank', 'Idea Cellular'] ['Jindal Steel & Power', 'DLF']
19 September 2014 ['Zee Entertainment Enterprises'] ['United Spirits']
28 March 2014 ['United Spirits', 'Tech Mahindra'] ['Ranbaxy Laboratories', 'JP Associates']
27 September 2013 ['Wipro'] ['Reliance Infrastructure']
1 April 2013 ['NMDC', 'IndusInd Bank'] ['Wipro', 'Siemens India']
28 September 2012 ['UltraTech Cement', 'Lupin'] ['Sterlite Industries', 'Steel Authority of India']
27 April 2012 ['Bank of Baroda', 'Asian Paints'] ['Reliance Power', 'Reliance Communications']
10 October 2011 ['Coal India'] ['Reliance Capital']
25 March 2011 ['Grasim Industries'] ['Suzlon']
1 October 2010 ['Sesa Goa', "Dr. Reddy's Laboratories", 'Bajaj Auto'] ['Unitech', 'Idea Cellular', 'ABB India']
8 April 2010 ['Kotak Mahindra Bank'] ['Grasim Industries']
20 October 2009 ['Jaiprakash Associates', 'IDFC'] ['Tata Communications', 'NALCO']
17 June 2009 ['Jindal Steel & Power'] ['Reliance Petroleum']
27 March 2009 ['Axis Bank'] ['Zee Entertainment Enterprises']
12 January 2009 ['Reliance Capital'] ['Satyam Computer Services']
10 September 2008 ['Reliance Power'] ["Dr. Reddy's Laboratories"]
14 March 2008 ['Power Grid', 'DLF'] ['GlaxoSmithKline Pharmaceuticals', 'Bajaj Auto']
12 December 2007 ['Idea Cellular', 'Cairn India'] ['MTNL', 'Hindustan Petroleum']
5 October 2007 ['Unitech'] ['IPCL']
24 September 2007 ['NTPC'] ['Dabur']
4 April 2007 ['Sterlite Industries', 'Reliance Petroleum'] ['Oriental Bank of Commerce', 'Jet Airways']
1 September 2006 ['Reliance Communications'] ['Tata Tea']
27 June 2006 ['Suzlon', 'Siemens India'] ['Tata Chemicals', 'Shipping Corporation of India']

In [ ]:
for i in yearwise_dict.values():
  print(len(i))

50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
51
51
52
52
52
52
52
52
52
52
52
52
52
52

In [ ]:
final_df = pd.DataFrame.from_dict(yearwise_dict, orient='index')
final_df.reset_index(inplace=True)
final_df = final_df.rename(columns={'index': 'Date'})

In [ ]:
final_df

,Date,0,1,2,3,4,5,6,7,8,...,42,43,44,45,46,47,48,49,50,51
0,28 March 2025,Adani Enterprises,Adani Ports & SEZ,Apollo Hospitals,Asian Paints,Axis Bank,Bajaj Auto,Bajaj Finance,Bajaj Finserv,Bharat Electronics,...,Tata Consumer Products,Tata Motors,Tata Steel,Tech Mahindra,Titan Company,Trent,UltraTech Cement,Wipro,None,None
1,30 September 2024,Adani Enterprises,Adani Ports & SEZ,Apollo Hospitals,Asian Paints,Axis Bank,Bajaj Auto,Bajaj Finance,Bajaj Finserv,Bharat Electronics,...,Tata Steel,Tech Mahindra,Titan Company,Trent,UltraTech Cement,Wipro,Britannia Industries,Bharat Petroleum,None,None
2,28 March 2024,Adani Enterprises,Adani Ports & SEZ,Apollo Hospitals,Asian Paints,Axis Bank,Bajaj Auto,Bajaj Finance,Bajaj Finserv,Bharti Airtel,...,Tech Mahindra,Titan Company,UltraTech Cement,Wipro,Britannia Industries,Bharat Petroleum,LTIMindtree,Divi's Laboratories,None,None
3,13 July 2023,Adani Enterprises,Adani Ports & SEZ,Apollo Hospitals,Asian Paints,Axis Bank,Bajaj Auto,Bajaj Finance,Bajaj Finserv,Bharti Airtel,...,Titan Company,UltraTech Cement,Wipro,Britannia Industries,Bharat Petroleum,LTIMindtree,Divi's Laboratories,UPL,None,None
4,30 September 2022,Adani Enterprises,Adani Ports & SEZ,Apollo Hospitals,Asian Paints,Axis Bank,Bajaj Auto,Bajaj Finance,Bajaj Finserv,Bharti Airtel,...,Titan Company,UltraTech Cement,Wipro,Britannia Industries,Bharat Petroleum,Divi's Laboratories,UPL,HDFC,None,None
5,31 March 2022,Adani Ports & SEZ,Apollo Hospitals,Asian Paints,Axis Bank,Bajaj Auto,Bajaj Finance,Bajaj Finserv,Bharti Airtel,Cipla,...,UltraTech Cement,Wipro,Britannia Industries,Bharat Petroleum,Divi's Laboratories,UPL,HDFC,Shree Cement,None,None
6,31 March 2021,Adani Ports & SEZ,Asian Paints,Axis Bank,Bajaj Auto,Bajaj Finance,Bajaj Finserv,Bharti Airtel,Cipla,Coal India,...,Wipro,Britannia Industries,Bharat Petroleum,Divi's Laboratories,UPL,HDFC,Shree Cement,Indian Oil Corporation,None,None
7,25 September 2020,Adani Ports & SEZ,Asian Paints,Axis Bank,Bajaj Auto,Bajaj Finance,Bajaj Finserv,Bharti Airtel,Cipla,Coal India,...,Britannia Industries,Bharat Petroleum,Divi's Laboratories,UPL,HDFC,Shree Cement,Indian Oil Corporation,GAIL,None,None
8,31 July 2020,Adani Ports & SEZ,Asian Paints,Axis Bank,Bajaj Auto,Bajaj Finance,Bajaj Finserv,Bharti Airtel,Cipla,Coal India,...,Bharat Petroleum,UPL,HDFC,Shree Cement,Indian Oil Corporation,GAIL,Bharti Infratel,Zee Entertainment Enterprises,None,None
9,19 March 2020,Adani Ports & SEZ,Asian Paints,Axis Bank,Bajaj Auto,Bajaj Finance,Bajaj Finserv,Bharti Airtel,Cipla,Coal India,...,UPL,HDFC,Shree Cement,Indian Oil Corporation,GAIL,Bharti Infratel,Zee Entertainment Enterprises,Vedanta,None,None
10,27 September 2019,Adani Ports & SEZ,Asian Paints,Axis Bank,Bajaj Auto,Bajaj Finance,Bajaj Finserv,Bharti Airtel,Cipla,Coal India,...,UPL,HDFC,Indian Oil Corporation,GAIL,Bharti Infratel,Zee Entertainment Enterprises,Vedanta,Yes Bank,None,None
11,29 March 2019,Adani Ports & SEZ,Asian Paints,Axis Bank,Bajaj Auto,Bajaj Finance,Bajaj Finserv,Bharti Airtel,Cipla,Coal India,...,HDFC,Indian Oil Corporation,GAIL,Bharti Infratel,Zee Entertainment Enterprises,Vedanta,Yes Bank,Indiabulls Housing Finance,None,None
12,28 September 2018,Adani Ports & SEZ,Asian Paints,Axis Bank,Bajaj Auto,Bajaj Finance,Bajaj Finserv,Bharti Airtel,Cipla,Coal India,...,Indian Oil Corporation,GAIL,Bharti Infratel,Zee Entertainment Enterprises,Vedanta,Yes Bank,Indiabulls Housing Finance,Hindustan Petroleum,None,None
13,2 April 2018,Adani Ports & SEZ,Asian Paints,Axis Bank,Bajaj Auto,Bajaj Finance,Bajaj Finserv,Bharti Airtel,Cipla,Coal India,...,GAIL,Bharti Infratel,Zee Entertainment Enterprises,Vedanta,Yes Bank,Indiabulls Housing Finance,Hindustan Petroleum,Lupin,None,None
14,29 September 2017,Adani Ports & SEZ,Asian Paints,Axis Bank,Bajaj Auto,Bajaj Finance,Bharti Airtel,Cipla,Coal India,Dr. Reddy's Laboratories,...,Vedanta,Yes Bank,Indiabulls Housing Finance,Hindustan Petroleum,Lupin,Bosch India,Aurobindo Pharma,Ambuja Cements,None,None
15,26 May 2017,Adani Ports & SEZ,Asian Paints,Axis Bank,Bajaj Auto,Bharti Airtel,Cipla,Coal India,Dr. Reddy's Laboratories,Eicher Motors,...,Indiabulls Housing Finance,Lupin,Bosch India,Aurobindo Pharma,Ambuja Cements,Tata Power,Bank of Baroda,ACC,None,None
16,31 March 2017,Adani Ports & SEZ,Asian Paints,Axis Bank,Bajaj Auto,Bharti Airtel,Cipla,Coal India,Dr. Reddy's Laboratories,Eicher Motors,...,Lupin,Bosch India,Aurobindo Pharma,Ambuja Cements,Tata Power,Bank of Baroda,ACC,Grasim Industries,None,None
17,1 April 2016,Adani Ports & SEZ,Asian Paints,Axis Bank,Bajaj Auto,Bharti Airtel,Cipla,Coal India,Dr. Reddy's Laboratories,Eicher Motors,...,Aurobindo Pharma,Ambuja Cements,Tata Power,Bank of Baroda,ACC,Grasim Industries,Idea Cellular,BHEL,None,None
18,28 September 2015,Adani Ports & SEZ,Asian Paints,Axis Bank,Bajaj Auto,Bharti Airtel,Cipla,Coal India,Dr. Reddy's Laboratories,HCLTech,...,Bank of Baroda,ACC,Grasim Industries,Idea Cellular,BHEL,Vedanta,Punjab National Bank,Cairn India,None,None
19,29 May 2015,Asian Paints,Axis Bank,Bajaj Auto,Bharti Airtel,Cipla,Coal India,Dr. Reddy's Laboratories,HCLTech,HDFC Bank,...,ACC,Grasim Industries,Idea Cellular,BHEL,Vedanta,Punjab National Bank,Cairn India,NMDC,None,None
20,27 March 2015,Asian Paints,Axis Bank,Bajaj Auto,Bharti Airtel,Cipla,Coal India,Dr. Reddy's Laboratories,HCLTech,HDFC Bank,...,Grasim Industries,Idea Cellular,BHEL,Vedanta,Punjab National Bank,Cairn India,NMDC,IDFC,None,None
21,19 September 2014,Asian Paints,Axis Bank,Bajaj Auto,Bharti Airtel,Cipla,Coal India,Dr. Reddy's Laboratories,HCLTech,HDFC Bank,...,BHEL,Vedanta,Punjab National Bank,Cairn India,NMDC,IDFC,Jindal Steel & Power,DLF,None,None
22,28 March 2014,Asian Paints,Axis Bank,Bajaj Auto,Bharti Airtel,Cipla,Coal India,Dr. Reddy's Laboratories,HCLTech,HDFC Bank,...,Vedanta,Punjab National Bank,Cairn India,NMDC,IDFC,Jindal Steel & Power,DLF,United Spirits,None,None
23,27 September 2013,Asian Paints,Axis Bank,Bajaj Auto,Bharti Airtel,Cipla,Coal India,Dr. Reddy's Laboratories,HCLTech,HDFC Bank,...,Punjab National Bank,Cairn India,NMDC,IDFC,Jindal Steel & Power,DLF,Ranbaxy Laboratories,JP Associates,None,None
24,1 April 2013,Asian Paints,Axis Bank,Bajaj Auto,Bharti Airtel,Cipla,Coal India,Dr. Reddy's Laboratories,HCLTech,HDFC Bank,...,Cairn India,NMDC,IDFC,Jindal Steel & Power,DLF,Ranbaxy Laboratories,JP Associates,Reliance Infrastructure,None,None
25,28 September 2012,Asian Paints,Axis Bank,Bajaj Auto,Bharti Airtel,Cipla,Coal India,Dr. Reddy's Laboratories,HCLTech,HDFC Bank,...,IDFC,Jindal Steel & Power,DLF,Ranbaxy Laboratories,JP Associates,Reliance Infrastructure,Wipro,Siemens India,None,None
26,27 April 2012,Asian Paints,Axis Bank,Bajaj Auto,Bharti Airtel,Cipla,Coal India,Dr. Reddy's Laboratories,HCLTech,HDFC Bank,...,DLF,Ranbaxy Laboratories,JP Associates,Reliance Infrastructure,Wipro,Siemens India,Sterlite Industries,Steel Authority of India,None,None
27,10 October 2011,Axis Bank,Bajaj Auto,Bharti Airtel,Cipla,Coal India,Dr. Reddy's Laboratories,HCLTech,HDFC Bank,Hero MotoCorp,...,JP Associates,Reliance Infrastructure,Wipro,Siemens India,Sterlite Industries,Steel Authority of India,Reliance Power,Reliance Communications,None,None
28,25 March 2011,Axis Bank,Bajaj Auto,Bharti Airtel,Cipla,Dr. Reddy's Laboratories,HCLTech,HDFC Bank,Hero MotoCorp,Hindalco Industries,...,Reliance Infrastructure,Wipro,Siemens India,Sterlite Industries,Steel Authority of India,Reliance Power,Reliance Communications,Reliance Capital,None,None
29,1 October 2010,Axis Bank,Bajaj Auto,Bharti Airtel,Cipla,Dr. Reddy's Laboratories,HCLTech,HDFC Bank,Hero MotoCorp,Hindalco Industries,...,Wipro,Siemens India,Sterlite Industries,Steel Authority of India,Reliance Power,Reliance Communications,Reliance Capital,Suzlon,Sesa Goa,None
30,8 April 2010,Axis Bank,Bharti Airtel,Cipla,HCLTech,HDFC Bank,Hero MotoCorp,Hindalco Industries,Hindustan Unilever,ICICI Bank,...,Sterlite Industries,Steel Authority of India,Reliance Power,Reliance Communications,Reliance Capital,Suzlon,Unitech,Idea Cellular,ABB India,None
31,20 October 2009,Axis Bank,Bharti Airtel,Cipla,HCLTech,HDFC Bank,Hero MotoCorp,Hindalco Industries,Hindustan Unilever,ICICI Bank,...,Steel Authority of India,Reliance Power,Reliance Communications,Reliance Capital,Suzlon,Unitech,Idea Cellular,ABB India,Grasim Industries,Jaiprakash Associates
32,17 June 2009,Axis Bank,Bharti Airtel,Cipla,HCLTech,HDFC Bank,Hero MotoCorp,Hindalco Industries,Hindustan Unilever,ICICI Bank,...,Reliance Power,Reliance Communications,Reliance Capital,Suzlon,Unitech,Idea Cellular,ABB India,Grasim Industries,Tata Communications,NALCO
33,27 March 2009,Axis Bank,Bharti Airtel,Cipla,HCLTech,HDFC Bank,Hero MotoCorp,Hindalco Industries,Hindustan Unilever,ICICI Bank,...,Reliance Communications,Reliance Capital,Suzlon,Unitech,Idea Cellular,ABB India,Grasim Industries,Tata Communications,NALCO,Reliance Petroleum
34,12 January 2009,Bharti Airtel,Cipla,HCLTech,HDFC Bank,Hero MotoCorp,Hindalco Industries,Hindustan Unilever,ICICI Bank,Infosys,...,Reliance Capital,Suzlon,Unitech,Idea Cellular,ABB India,Grasim Industries,Tata Communications,NALCO,Reliance Petroleum,Zee Entertainment Enterprises
35,10 September 2008,Bharti Airtel,Cipla,HCLTech,HDFC Bank,Hero MotoCorp,Hindalco Industries,Hindustan Unilever,ICICI Bank,Infosys,...,Suzlon,Unitech,Idea Cellular,ABB India,Grasim Industries,Tata Communications,NALCO,Reliance Petroleum,Zee Entertainment Enterprises,Satyam Computer Services
36,14 March 2008,Bharti Airtel,Cipla,HCLTech,HDFC Bank,Hero MotoCorp,Hindalco Industries,Hindustan Unilever,ICICI Bank,Infosys,...,Unitech,Idea Cellular,ABB India,Grasim Industries,Tata Communications,NALCO,Reliance Petroleum,Zee Entertainment Enterprises,Satyam Computer Services,Dr. Reddy's Laboratories
37,12 December 2007,Bharti Airtel,Cipla,HCLTech,HDFC Bank,Hero MotoCorp,Hindalco Industries,Hindustan Unilever,ICICI Bank,Infosys,...,ABB India,Grasim Industries,Tata Communications,NALCO,Reliance Petroleum,Zee Entertainment Enterprises,Satyam Computer Services,Dr. Reddy's Laboratories,GlaxoSmithKline Pharmaceuticals,Bajaj Auto
38,5 October 2007,Bharti Airtel,Cipla,HCLTech,HDFC Bank,Hero MotoCorp,Hindalco Industries,Hindustan Unilever,ICICI Bank,Infosys,...,Tata Communications,NALCO,Reliance Petroleum,Zee Entertainment Enterprises,Satyam Computer Services,Dr. Reddy's Laboratories,GlaxoSmithKline Pharmaceuticals,Bajaj Auto,MTNL,Hindustan Petroleum
39,24 September 2007,Bharti Airtel,Cipla,HCLTech,HDFC Bank,Hero MotoCorp,Hindalco Industries,Hindustan Unilever,ICICI Bank,Infosys,...,NALCO,Reliance Petroleum,Zee Entertainment Enterprises,Satyam Computer Services,Dr. Reddy's Laboratories,GlaxoSmithKline Pharmaceuticals,Bajaj Auto,MTNL,Hindustan Petroleum,IPCL
40,4 April 2007,Bharti Airtel,Cipla,HCLTech,HDFC Bank,Hero MotoCorp,Hindalco Industries,Hindustan Unilever,ICICI Bank,Infosys,...,Reliance Petroleum,Zee Entertainment Enterprises,Satyam Computer Services,Dr. Reddy's Laboratories,GlaxoSmithKline Pharmaceuticals,Bajaj Auto,MTNL,Hindustan Petroleum,IPCL,Dabur
41,1 September 2006,Bharti Airtel,Cipla,HCLTech,HDFC Bank,Hero MotoCorp,Hindalco Industries,Hindustan Unilever,ICICI Bank,Infosys,...,Satyam Computer Services,Dr. Reddy's Laboratories,GlaxoSmithKline Pharmaceuticals,Bajaj Auto,MTNL,Hindustan Petroleum,IPCL,Dabur,Oriental Bank of Commerce,Jet Airways
42,27 June 2006,Bharti Airtel,Cipla,HCLTech,HDFC Bank,Hero MotoCorp,Hindalco Industries,Hindustan Unilever,ICICI Bank,Infosys,...,Dr. Reddy's Laboratories,GlaxoSmithKline Pharmaceuticals,Bajaj Auto,MTNL,Hindustan Petroleum,IPCL,Dabur,Oriental Bank of Commerce,Jet Airways,Tata Tea

In [ ]:
final_df.to_csv('yearwise_niftyfinall.csv', index=False)